### Register Admin
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@test.com",
  "password": "1234",
  "role": "admin"
}

###

### Register Student
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Ron",
  "email": "ron@gmail.com",
  "password": "ron@1234",
  "role": "student"
}

###

### Create Application
POST http://localhost:5000/api/applications
Content-Type: application/json

{
  "user_id": 3,
  "admission_type": "UG",
  "university": "VNR"
}

###

### Get All Applications (ADMIN ONLY)
GET http://localhost:5000/api/applications?user_id=1

###

### Update Application Status
PUT http://localhost:5000/api/applications/1
Content-Type: application/json

{
  "status": "approved"
}
